// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YksProject.DataAccessLayer.Concrete;

namespace YksProject.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240307142036_mig3")]
    partial class mig3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Abonelik", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbonePaketAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbonePaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AbonelikUcreti")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Abonelik");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.BaseModel", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AktifEdenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("AktifMi")
                        .HasColumnType("int");

                    b.Property<DateTime>("AktiflikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncellendiMi")
                        .HasColumnType("int");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("SilindiMi")
                        .HasColumnType("int");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("BaseModel");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.GirilenSinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavinTipi")
                        .HasColumnType("int");

                    b.Property<DateTime>("SinavBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinavSonucu")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("GirilenSinav");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Kisi", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AboneTipi")
                        .HasColumnType("int");

                    b.Property<int>("KisiAboneMi")
                        .HasColumnType("int");

                    b.Property<DateTime>("KisiAbonelikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiGirdigiSinavlar")
                        .HasColumnType("int");

                    b.Property<string>("KisiImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiObpDegeri")
                        .HasColumnType("int");

                    b.Property<DateTime>("KisiSonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisiSoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiYasi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Kisi");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Referanslarimiz", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReferansAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansPuani")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("Referanslarimiz");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Sinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinavKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinavSüresi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Sinav");
                });
#pragma warning restore 612, 618
        }
    }
}
