// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YksProject.DataAccessLayer.Concrete;

namespace YksProject.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240426144651_UyelikPackageAdded")]
    partial class UyelikPackageAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Abonelik", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbonePaketAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbonePaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AbonelikUcreti")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Abonelik");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Bolumler", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAdKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Dersler", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersSoruSayisi")
                        .HasColumnType("int");

                    b.Property<int>("DersiEkleyenKurumID")
                        .HasColumnType("int");

                    b.Property<bool>("DersiKurumMuEkledi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("IlgiliSinavTipiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.GirilenSinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("GirilenSinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavinTipi")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinavSonucu")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("GirilenSinav");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Kisi", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("KisiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiBolumID")
                        .HasColumnType("int");

                    b.Property<int>("KisiCinsiyetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KisiDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisiEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiEmailChecked")
                        .HasColumnType("bit");

                    b.Property<int>("KisiIlgiliKurumID")
                        .HasColumnType("int");

                    b.Property<string>("KisiImageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiKullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiKurumSahibiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("KisiMezunOgrencisiMi")
                        .HasColumnType("bit");

                    b.Property<int>("KisiObpDegeri")
                        .HasColumnType("int");

                    b.Property<string>("KisiPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiSoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiTelNoChecked")
                        .HasColumnType("bit");

                    b.Property<int>("KisiYasi")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Kisi");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Kurum", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KurumAbonelikBasTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KurumAbonelikBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KurumAbonelikOgrenciSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KurumAbonelikTipi")
                        .HasColumnType("int");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumImageID")
                        .HasColumnType("int");

                    b.Property<string>("KurumImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumSahibiID")
                        .HasColumnType("int");

                    b.Property<int>("KurumTipi")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Kurum");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.MedyaKutuphanesi", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("MedyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedyaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("MedyaKutuphanesi");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.PaketUyeTipleri", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UyeTipiAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeTipiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("PaketUyeTipleri");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Referanslarimiz", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferansAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansPuani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Referanslarimiz");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Roller", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Sinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SinavBaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SinavBittiMi")
                        .HasColumnType("bit");

                    b.Property<string>("SinavKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinavSüresi")
                        .HasColumnType("int");

                    b.Property<int>("SinaviEkleyenKurumID")
                        .HasColumnType("int");

                    b.Property<bool>("SinaviKurumMuEkledi")
                        .HasColumnType("bit");

                    b.HasKey("TabloID");

                    b.ToTable("Sinav");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.UyelikPaketleri", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaketAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketImageID")
                        .HasColumnType("int");

                    b.Property<string>("PaketImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketIndirimOrani")
                        .HasColumnType("int");

                    b.Property<int>("PaketUcreti")
                        .HasColumnType("int");

                    b.Property<int>("PaketUyeSayısı")
                        .HasColumnType("int");

                    b.Property<int>("PaketUyeTipiID")
                        .HasColumnType("int");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("UyelikPaketleri");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Yapilacaklar", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GorevYapilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YapilacakGorevAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevGun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevGunNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevIkon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapildiMi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Yapilacaklar");
                });
#pragma warning restore 612, 618
        }
    }
}
