// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YksProject.DataAccessLayer.Concrete;

namespace YksProject.DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240718101029_KurumTableRowAdded")]
    partial class KurumTableRowAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Abonelik", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AbonePaketAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbonePaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AbonelikUcreti")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Abonelik");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.AytEaGirisTablosu", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AytCografya1DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytCografya1NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytCografya1ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytCografya1YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytEdebiyatDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytEdebiyatNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytEdebiyatToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytEdebiyatYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytMatDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytMatNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytMatToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytMatYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih1DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytTarih1NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytTarih1ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih1YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("AytEaGirisTablosu");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.AytSayGirisTablosu", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AytBiyolojiDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytBiyolojiNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytBiyolojiToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytBiyolojiYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytFizikDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytFizikNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytFizikToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytFizikYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytKimyaDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytKimyaNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytKimyaToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytKimyaYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytMatDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytMatNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytMatToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytMatYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("AytSayGirisTablosu");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.AytSozelGirisTablosu", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AytCografya1DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytCografya1NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytCografya1ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytCografya1YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytCografya2DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytCografya2NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytCografya2ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytCografya2YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytDinDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytDinNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytDinToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytDinYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytEdebiyatDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytEdebiyatNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytEdebiyatToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytEdebiyatYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytFelsefeDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytFelsefeNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytFelsefeToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytFelsefeYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih1DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytTarih1NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytTarih1ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih1YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih2DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytTarih2NetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytTarih2ToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytTarih2YanlisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("AytSozelGirisTablosu");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.AytYDGirisTablosu", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AytDilDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("AytDilNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("AytDilToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("AytDilYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("AytYDGirisTablosu");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Bildirimler", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AliciKisiID")
                        .HasColumnType("int");

                    b.Property<string>("BildirimAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BildirimAliciOkuduMu")
                        .HasColumnType("bit");

                    b.Property<string>("BildirimBasligi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GonderenKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Bolumler", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAdKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Dersler", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DersAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersBolumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.GirilenSinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("GirilenSinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavinTipi")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SinavGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinavSonucu")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("GirilenSinav");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.HomePost", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostAciklamasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostGorulmeSayisi")
                        .HasColumnType("int");

                    b.Property<int>("PostMedyaID")
                        .HasColumnType("int");

                    b.Property<string>("PostMedyaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostSahibi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostTiklanmaSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("PostYayindaMi")
                        .HasColumnType("bit");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("HomePost");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Kisi", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("KisiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KisiBolumID")
                        .HasColumnType("int");

                    b.Property<int>("KisiCinsiyetID")
                        .HasColumnType("int");

                    b.Property<DateTime>("KisiDogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KisiEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiEmailChecked")
                        .HasColumnType("bit");

                    b.Property<int>("KisiIlgiliKurumID")
                        .HasColumnType("int");

                    b.Property<string>("KisiImageID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiKullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiKurumSahibiMi")
                        .HasColumnType("bit");

                    b.Property<bool>("KisiMezunOgrencisiMi")
                        .HasColumnType("bit");

                    b.Property<int>("KisiObpDegeri")
                        .HasColumnType("int");

                    b.Property<string>("KisiPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiSoyAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisiTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("KisiTelNoChecked")
                        .HasColumnType("bit");

                    b.Property<int>("KisiYasi")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UserOnlineMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UserSonCikisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UserSonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserToplamGirisSayisi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Kisi");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Konular", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("Konu1SeneSoruSayisi")
                        .HasColumnType("int");

                    b.Property<int>("Konu2SeneSoruSayisi")
                        .HasColumnType("int");

                    b.Property<int>("Konu3SeneSoruSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KonuAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuAciklamasiYapanKisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuAciklamasiYapanKisiRolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KonuDersID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Kurum", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("KurumAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumImageID")
                        .HasColumnType("int");

                    b.Property<string>("KurumImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumInstaKullaniciAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumMaxOgrenciLimiti")
                        .HasColumnType("int");

                    b.Property<int>("KurumOgrenciSayisi")
                        .HasColumnType("int");

                    b.Property<string>("KurumPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumSahibiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KurumSahibiEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KurumSahibiTelNo")
                        .HasColumnType("int");

                    b.Property<int>("KurumTelNo")
                        .HasColumnType("int");

                    b.Property<int>("KurumTipiID")
                        .HasColumnType("int");

                    b.Property<string>("KurumWebSiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Kurum");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.MedyaKutuphanesi", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<string>("MedyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedyaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("MedyaKutuphanesi");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Message", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("MesajAliciID")
                        .HasColumnType("int");

                    b.Property<bool>("MesajAliciOkuduMu")
                        .HasColumnType("bit");

                    b.Property<string>("MesajGonderenKisiImageUrl")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("MesajGondericiID")
                        .HasColumnType("int");

                    b.Property<string>("MesajText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.PaketUyeTipleri", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("UyeTipiAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeTipiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("PaketUyeTipleri");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Referanslarimiz", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferansAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansPuani")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferansRolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Referanslarimiz");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Roller", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RolAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RolAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Sinav", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SinavKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SinavSüresi")
                        .HasColumnType("int");

                    b.Property<int>("SinavTipiID")
                        .HasColumnType("int");

                    b.Property<int>("SinaviEkleyenKurumID")
                        .HasColumnType("int");

                    b.Property<bool>("SinaviKurumMuEkledi")
                        .HasColumnType("bit");

                    b.HasKey("TabloID");

                    b.ToTable("Sinav");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.SinavTipleri", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavTipiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TabloID");

                    b.ToTable("SinavTipleri");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.TytSinavGirisTablosu", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BaslangicZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GirenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("GirilenSinavID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SinavAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TytFenDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("TytFenNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("TytFenToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("TytFenYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TytMatematikDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("TytMatematikNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("TytMatematikToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("TytMatematikYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TytSosyalDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("TytSosyalNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("TytSosyalToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("TytSosyalYanlisSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TytTurkceDogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("TytTurkceNetSayisi")
                        .HasColumnType("float");

                    b.Property<int>("TytTurkceToplamDakika")
                        .HasColumnType("int");

                    b.Property<int>("TytTurkceYanlisSayisi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("TytSinavGirisTablosu");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.UyelikPaketleri", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaketAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketImageID")
                        .HasColumnType("int");

                    b.Property<string>("PaketImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaketIndirimOrani")
                        .HasColumnType("int");

                    b.Property<int>("PaketUcreti")
                        .HasColumnType("int");

                    b.Property<int>("PaketUyeSayısı")
                        .HasColumnType("int");

                    b.Property<int>("PaketUyeTipiID")
                        .HasColumnType("int");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TabloID");

                    b.ToTable("UyelikPaketleri");
                });

            modelBuilder.Entity("YksProject.EntityLayer.Concrete.Yapilacaklar", b =>
                {
                    b.Property<int>("TabloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GorevYapilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuncelleyenKisiID")
                        .HasColumnType("int");

                    b.Property<int>("OlusturanKisiID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SilenKisiID")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("YapilacakGorevAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevGun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevGunNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilacakGorevIkon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YapildiMi")
                        .HasColumnType("int");

                    b.HasKey("TabloID");

                    b.ToTable("Yapilacaklar");
                });
#pragma warning restore 612, 618
        }
    }
}
